language: python
python:
  - "3.8"
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py3
  - TOXENV=lint
  # - TOXENV=integration # requires a remote lxd setup

install:
  - travis_retry pip install tox
  - pip install codecov
script:
  - tox
  - test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
cache:
  directories:
    - $HOME/.cache/pip
after_success:
  - codecov
