language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
stages:
  - lint
  - test
install: pip install tox codecov
jobs:
  fast_finish: true
  include:
    - stage: lint
      script: tox -e lint
      python: "3.6"
script:
  - tox -e py
  - test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
cache:
  directories:
    - $HOME/.cache/pip
after_success: codecov
